# InvenioDRM Starter staging environment
#
# Usage::
#
#   $ docker compose up -d
#
# The following services are included:
# - Reverse Proxy with SSL termination: Traefik (exposed ports: 80, 443, 8080)
# - Web application: Nginx/Gunicorn (exposed port: not exposed)
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL) (exposed port: 5432)
# - Message queue: Redis (exposed port: 6379)
# - Search platform: (OpenSearch) (exposed ports: 9200, 9300)

version: '3.8'
services:
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80

      # use default Traefic TLS certificate (browser may give warnings)
      - --entrypoints.websecure.address=:443
      - --api.insecure
    labels:
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  web:
    build:
      context: ./
    image: invenio-rdm-starter:latest
    ports:
      - "5000"
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL="
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL="
      - "INVENIO_CELERY_RESULTpro_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://invenio-rdm-starter:invenio-rdm-starter@db/invenio-rdm-starter"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  worker:
    build:
      context: ./
    command: ["celery -A invenio_app.celery worker --beat --loglevel=INFO"]
    image: invenio-rdm-starter:latest
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL="
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=redis://cache:6379/1"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://invenio-rdm-starter:invenio-rdm-starter@db/invenio-rdm-starter"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  cache:
    image: redis:7.2
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:16.2
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=inveniordm"
      - "POSTGRES_PASSWORD=inveniordm"
      - "POSTGRES_DB=inveniordm"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d/inveniordm.sql:/docker-entrypoint-initdb.d/inveniordm.sql
  search:
    image: opensearchproject/opensearch:2.12.0
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    volumes:
      - ./docker/opensearch:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
volumes:
  static_data:
  uploaded_data:
  archived_data:
