# InvenioDRM Starter Docker Compose
#
# Usage::
#
#   $ docker compose up -d
#
# The following services are included:
# - Web application: Nginx/Gunicorn (exposed port: 8080)
# - DB: (PostgresSQL) (exposed port: 5432)
# - Cache: Redis (exposed port: 6379)
# - Message queue: Redis (exposed port: 6379)
# - Search platform: (OpenSearch) (exposed ports: 9200, 9300)

services:
  nginx:
    image: nginx:1.25-bookworm
    restart: "unless-stopped"
    ports:
      - "9000:9000"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/ssl/certs/
      - "./docker/nginx/templates:/etc/nginx/templates/"
      - static_data:/opt/invenio/var/instance/static
    env_file:
      - .env.default
      - .env
  web:
    image: ghcr.io/front-matter/invenio-rdm-starter:latest
    ports:
      - "5000"
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    env_file:
      - .env.default
      - .env
  # worker:
  #   command: ["celery -A invenio_app.celery worker --beat --loglevel=INFO"]
  #   image: ghcr.io/front-matter/invenio-rdm-starter:latest
  #   volumes:
  #     - uploaded_data:/opt/invenio/var/instance/data
  #   depends_on:
  #     search:
  #       condition: service_started
  #     cache:
  #       condition: service_started
  #     db:
  #       condition: service_started
  cache:
    image: redis:7.2
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:16.2
    restart: "unless-stopped"
    env_file:
      - .env.default
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d/inveniordm.sql:/docker-entrypoint-initdb.d/inveniordm.sql
  search:
    image: opensearchproject/opensearch:2.12.0
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    volumes:
      - ./docker/opensearch:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
volumes:
  static_data:
  uploaded_data:
  archived_data:
