# InvenioDRM Starter Docker Compose
#
# Usage::
#
#   $ docker compose up -d
#
# The following services are included:
# - Web application: Caddy/Gunicorn (exposed port: 8080)
# - DB: (PostgresSQL) (exposed port: 5432)
# - Cache: Redis (exposed port: 6379)
# - Message queue: Redis (exposed port: 6379)
# - Search platform: (OpenSearch) (exposed ports: 9200, 9300)

services:
  proxy:
    image: caddy:2.7.6
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - static_data:/opt/invenio/var/instance/static
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env.default
      - .env
  web:
    image: ghcr.io/front-matter/invenio-rdm-starter:latest
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    env_file:
      - .env.default
      - .env
    environment:
      - INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/
      - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/
      - INVENIO_CACHE_REDIS_URL=redis://cache:6379/0
      - INVENIO_CACHE_TYPE=redis
      - INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1
      - INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2
      - INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3
      - INVENIO_SEARCH_HOSTS=['search:9200']
      - INVENIO_SECRET_KEY=${INVENIO_SECRET_KEY}
      - INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inveniordm:inveniordm@db/inveniordm
      - INVENIO_WSGI_PROXIES=2
      - INVENIO_THEME_SHOW_FRONTPAGE_INTRO_SECTION=False
      - INVENIO_MAIL_SUPPRESS_SEND=True
  worker:
    command: "celery -A invenio_app.celery worker --beat --loglevel=INFO"
    image: ghcr.io/front-matter/invenio-rdm-starter:latest
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
    environment:
      - INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/
      - INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2
  mq:
    image: rabbitmq:3.13-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
  cache:
    image: redis:7.2.5-bookworm
    restart: "unless-stopped"
    ports:
      - "6379:6379"
  db:
    image: postgres:16.2
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d/inveniordm.sql:/docker-entrypoint-initdb.d/inveniordm.sql
  search:
    image: opensearchproject/opensearch:2.12.0
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    volumes:
      - ./docker/opensearch:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
volumes:
  static_data:
  uploaded_data:
  archived_data:
  caddy_data:
  caddy_config:
