version: "3.8"

services:
  proxy:
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - "8080:80"        # change to 80:80 if free
      # - "8443:443"     # enable after you add TLS in Caddyfile
    volumes:
      - ./caddy:/etc/caddy        # directory -> directory
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  web:
    image: ghcr.io/front-matter/invenio-rdm-starter:v12.1.0.0
    restart: unless-stopped
    pull_policy: if_not_present
    environment:
      INVENIO_APP_TRUSTED_HOSTS: "['0.0.0.0','localhost','127.0.0.1']"
      INVENIO_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://inveniordm:inveniordm@db/inveniordm
      INVENIO_BABEL_DEFAULT_LOCALE: en
      INVENIO_BABEL_DEFAULT_TIMEZONE: UTC
      INVENIO_CACHE_TYPE: redis
      INVENIO_CACHE_REDIS_URL: redis://cache:6379/0
      INVENIO_ACCOUNTS_SESSION_REDIS_URL: redis://cache:6379/1
      INVENIO_CELERY_RESULT_BACKEND: redis://cache:6379/2
      INVENIO_RATELIMIT_STORAGE_URL: redis://cache:6379/3
      INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL: redis://cache:6379/4
      INVENIO_BROKER_URL: redis://cache:6379/5            # use redis, no RabbitMQ service
      INVENIO_CELERY_BROKER_URL: redis://cache:6379/6
      INVENIO_MAIL_SUPPRESS_SEND: "True"
      INVENIO_WSGI_PROXIES: "4"
      INVENIO_SECRET_KEY: changeme
      INVENIO_THEME_LOGO: images/invenio-rdm-white.svg
      INVENIO_THEME_SITENAME: InvenioRDM Starter
      INVENIO_THEME_FRONTPAGE_TITLE: InvenioRDM Starter
      INVENIO_THEME_FRONTPAGE_SUBTITLE: A starter project for the turn-key research data management repository.
      INVENIO_THEME_SHOW_FRONTPAGE_INTRO_SECTION: "False"
      INVENIO_SITE_UI_URL: https://localhost
      INVENIO_SITE_API_URL: https://localhost/api
      INVENIO_RDM_ALLOW_METADATA_ONLY_RECORDS: "True"
      INVENIO_RDM_ALLOW_RESTRICTED_RECORDS: "True"
      INVENIO_RDM_ALLOW_EXTERNAL_DOI_VERSIONING: "True"
      INVENIO_RDM_CITATION_STYLES_DEFAULT: apa
      INVENIO_SEARCH_HOSTS: "['search:9200']"
      INVENIO_SEARCH_INDEX_PREFIX: invenio-rdm-
      INVENIO_LOGGING_CONSOLE_LEVEL: WARNING
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started

  worker:
    image: ghcr.io/front-matter/invenio-rdm-starter:v12.1.0.0
    restart: unless-stopped
    pull_policy: if_not_present
    command: "celery -A invenio_app.celery worker --beat --events --loglevel=WARNING"
    environment:
      INVENIO_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://inveniordm:inveniordm@db/inveniordm
      INVENIO_SEARCH_HOSTS: "['search:9200']"
      INVENIO_SEARCH_INDEX_PREFIX: invenio-rdm-
      INVENIO_CACHE_TYPE: redis
      INVENIO_CACHE_REDIS_URL: redis://cache:6379/0
      INVENIO_ACCOUNTS_SESSION_REDIS_URL: redis://cache:6379/1
      INVENIO_CELERY_RESULT_BACKEND: redis://cache:6379/2
      INVENIO_RATELIMIT_STORAGE_URL: redis://cache:6379/3
      INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL: redis://cache:6379/4
      INVENIO_BROKER_URL: redis://cache:6379/5
      INVENIO_CELERY_BROKER_URL: redis://cache:6379/6
      INVENIO_MAIL_SUPPRESS_SEND: "True"
      INVENIO_FILES_REST_STORAGE_FACTORY: invenio_s3.s3fs_storage_factory
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
      db:
        condition: service_started

  cache:
    image: valkey/valkey:7.2.5-bookworm
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:17.4-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-inveniordm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-inveniordm}
      POSTGRES_DB: ${POSTGRES_DB:-inveniordm}
    # do NOT publish 5432; keep internal

  search:
    image: opensearchproject/opensearch:2.12.0
    restart: unless-stopped
    environment:
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      discovery.type: single-node
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  uploaded_data:
  archived_data:
  caddy_data:
  caddy_config:
