# fly.toml app configuration file generated for invenio-rdm-starter on 2024-06-18T11:07:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'invenio-rdm-starter'
primary_region = 'fra'

[build]
  image = "ghcr.io/front-matter/invenio-rdm-starter:latest"

[env]
  # Flask-Babel
  INVENIO_BABEL_DEFAULT_LOCALE = "en"
  INVENIO_BABEL_DEFAULT_TIMEZONE = "UTC"

  # Invenio-Records-Resources
  INVENIO_SITE_API_URL = "https://beta.rogue-scholar.org/api"
  INVENIO_SITE_UI_URL = "https://beta.rogue-scholar.org"

  # Invenio-Search
  INVENIO_SEARCH_INDEX_PREFIX = "invenio-rdm-"

  # Invenio-Theme
  INVENIO_THEME_FRONTPAGE_TITLE = "Science blogging on steroids."
  INVENIO_THEME_FRONTPAGE_SUBTITLE = "The Rogue Scholar science blog archive improves science blogs in important ways, including full-text search, long-term archiving, DOIs and metadata, and communities."
  INVENIO_THEME_LOGO = "images/rogue-scholar.svg"
  INVENIO_THEME_SHOW_FRONTPAGE_INTRO_SECTION = "False"
  INVENIO_THEME_SITENAME = "Rogue Scholar"

[processes]
  web = "gunicorn invenio_app.wsgi:application --bind 0.0.0.0:5000 --workers 4"
  worker = "celery -A invenio_app.celery worker --beat --events --loglevel=WARNING"

[http_service]
  internal_port = 5000
  # force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

# [[http_service.checks]]
#  grace_period = "10s"
#  interval = "30s"
#  method = "GET"
#  timeout = "5s"
#  path = "/"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
