site_name: InvenioRDM Starter
site_dir: _site
site_url: https://starter.front-matter.io
repo_url: https://github.com/front-matter/invenio-rdm-starter
edit_uri: edit/main/docs/
repo_name: front-matter/invenio-rdm-starter
copyright: Copyright &copy; 2024 Front Matter
plugins:
  - search
  - material-plausible
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  logo: assets/logo.png
  palette:
    primary: custom
  features:
    - content.code.copy
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<info@front-matter.io>
    - icon: fontawesome/brands/mastodon 
      link: https://mozilla.org/@martin
    - icon: fontawesome/brands/github 
      link: https://github.com/front-matter/invenio-rdm-starter
  analytics:
    provider: plausible
    domain: starter.front-matter.io
extra_css:
  - stylesheets/extra.css
