[project]
name = "invenio-rdm-starter"
version = "12.1.0.0"
description = "Starter for the invenio-rdm turn-key research data management repository"
authors = [{ name = "Martin Fenner", email = "martin@front-matter.io" }]
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "invenio-app-rdm~=12.1.0",
    "invenio-search[opensearch2]~=2.4.1",
    "invenio-logging[sentry]>=2.1.5,<3.0.0",
    "invenio-s3~=1.0.7",
    "gunicorn~=23.0.0",
    "ruff>=0.11.0",
]

[tool.hatch.build.targets.wheel]
packages = ["./site"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 79
include = ["pyproject.toml", "site/**/*.py"]
