[project]
name = "invenio-rdm-starter"
version = "12.1.0.1"
description = "Starter for the invenio-rdm turn-key research data management repository"
authors = [{ name = "Martin Fenner", email = "martin@front-matter.io" }]
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "invenio-app-rdm~=12.1.0",
    "invenio-search[opensearch2]~=2.4.1",
    "invenio-s3~=1.0.7",
    "invenio-assets~=3.2.0",
    "gunicorn~=23.0.0",
    "ruff>=0.11.0",
    "invenio-rest>=1.5.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["site/invenio_rdm_starter/*.py"]

[tool.ruff]
line-length = 79
include = ["pyproject.toml", "site/**/*.py"]

[project.optional-dependencies]
docs = ["mkdocs-material>=8.5.11"]

[tool.uv.sources]
invenio-rest = { git = "https://github.com/front-matter/invenio-rest", branch = "maint-1.x" }
