[tool.poetry]
name = "invenio-rdm-starter"
version = "0.1.0"
description = "Starter for the Tturn-key research data management repository"
authors = ["Martin Fenner <martin@front-matter.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.8"
invenio-app-rdm = "^11.0.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.1.7"
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
