[tool.poetry]
name = "invenio-rdm-starter"
version = "0.3.0"
description = "Starter for the turn-key research data management repository"
authors = ["Martin Fenner <martin@front-matter.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
invenio-app-rdm = "12.0.*"
invenio-search = "^2.3.1"
opensearch-dsl = "^2.1.0"
gunicorn = "^21.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
