[tool.poetry]
name = "invenio-rdm-starter"
version = "0.2.0"
description = "Starter for the Tturn-key research data management repository"
authors = ["Martin Fenner <martin@front-matter.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.18"
invenio-app-rdm = "^12.0.0b3.dev3"
# invenio-rdm-starter = {editable="True", path="./site"}
uwsgi = ">=2.0"
uwsgitop = ">=0.11"
uwsgi-tools = ">=1.1.1"
greenlet = "^3.0.3"
invenio-app = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
