[project]
name = "invenio-rdm-starter"
version = "0.2.0"
description = "Starter for the turn-key research data management repository"
authors = [
    { name = "Martin Fenner", email = "martin@front-matter.io" }
]
dependencies = [
    "invenio-app-rdm>=12.0.0rc2,<12.1.dev0",
    "invenio-search[opensearch2]~=2.3.1",
    "invenio-cache~=1.3.0",
    "importlib-metadata~=7.1.0",
    "gunicorn~=22.0.0",
    "nodeenv~=1.9.1",
]
readme = "README.md"
requires-python = ">= 3.9"
license = "MIT"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
virtual = true
managed = true
dev-dependencies = [
    "ruff>=0.4.8",
    "pytest>=7.4.3",
]

[tool.ruff]
line-length = 79
include = ["pyproject.toml", "src/**/*.py"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/invenio_rdm_starter"]
