service: starter
image: front-matter/invenio-rdm-starter
servers:
  web:
    hosts:
      - 176.9.24.117
    labels:
      service: invenio-rdm-starter
  worker:
    hosts:
      - 176.9.24.117
    cmd: celery -A invenio_app.celery worker --beat --events

proxy:
  ssl: true
  host: demo.front-matter.io
  ssl_redirect: true
  forward_headers: true
  app_port: 5000
  healthcheck:
    path: /ping
    interval: 30
    timeout: 10

registry:
  server: ghcr.io
  username: mfenner
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .
  remote: ssh://root@176.9.24.117
  local: false
  cache:
    type: registry

env:
  clear:
    INVENIO_SITE_UI_URL: https://demo.front-matter.io
    INVENIO_SITE_API_URL: https://demo.front-matter.io/api
    INVENIO_WSGI_PROXIES: 4
    # accessories db, cache, search
    POSTGRES_DB: starter
    INVENIO_CACHE_TYPE: redis
    INVENIO_CACHE_REDIS_URL: redis://inveniordm-cache:6379/0
    INVENIO_ACCOUNTS_SESSION_REDIS_URL: redis://inveniordm-cache:6379/1
    INVENIO_CELERY_RESULT_BACKEND: redis://inveniordm-cache:6379/2
    INVENIO_RATELIMIT_STORAGE_URL: redis://inveniordm-cache:6379/3
    INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL: redis://inveniordm-cache:6379/4
    INVENIO_BROKER_URL: redis://inveniordm-cache:6379/5
    INVENIO_CELERY_BROKER_URL: redis://inveniordm-cache:6379/5
    INVENIO_SEARCH_HOSTS: inveniordm-search:9200
    INVENIO_SEARCH_INDEX_PREFIX: invenio-rdm-starter-
    INVENIO_OAISERVER_ID_PREFIX: invenio-rdm-starter-
    INVENIO_THEME_SITENAME: InvenioRDM Starter
    INVENIO_THEME_FRONTPAGE_TITLE: "InvenioRDM Starter"
    INVENIO_THEME_FRONTPAGE_SUBTITLE: "A starter project for the turn-key research data management repository."
    INVENIO_THEME_LOGO: images/invenio-rdm-white.svg
    INVENIO_RDM_ALLOW_EXTERNAL_DOI_VERSIONING: False
    # mail
    INVENIO_MAIL_DEFAULT_SENDER: info@front-matter.io
    INVENIO_SECURITY_EMAIL_SENDER: info@front-matter.io
    INVENIO_APP_RDM_ADMIN_EMAIL_RECIPIENT: info@front-matter.io
  secret:
    - INVENIO_SQLALCHEMY_DATABASE_URI
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - OPENSEARCH_INITIAL_ADMIN_PASSWORD
    - INVENIO_SECRET_KEY
    - INVENIO_SENTRY_DSN
    - INVENIO_APP_ALLOWED_HOSTS
    # mail
    - INVENIO_MAIL_SERVER
    - INVENIO_MAIL_PORT
    - INVENIO_MAIL_USERNAME
    - INVENIO_MAIL_PASSWORD
    - INVENIO_MAIL_USE_TLS
    # oauth authentication
    - INVENIO_OAUTHCLIENT_REMOTE_APPS
    - INVENIO_ORCID_APP_CREDENTIALS
    - INVENIO_GITHUB_APP_CREDENTIALS
accessories:
  db:
    image: paradedb/paradedb:0.16.0-pg17
    host: 176.9.24.117
    port: 5432
    directories:
      - data:/var/lib/postgresql/data
    env:
      clear:
        POSTGRES_DB: starter
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
  cache:
    image: valkey/valkey:7.2.5
    host: 176.9.24.117
    port: 6379
    directories:
      - data:/data
  search:
    image: opensearchproject/opensearch:2.18.0
    host: 176.9.24.117
    port: 9200
    env:
      clear:
        discovery.type: single-node
        bootstrap.memory_lock: true
        OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISABLE_INSTALL_DEMO_CONFIG: true
        DISABLE_SECURITY_PLUGIN: true
      secret:
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD
    options:
      memory: 4g
      publish:
        - 9600:9600
volumes:
  - uploaded_data:/opt/invenio/var/instance/data
  - archived_data:/opt/invenio/var/instance/archive
deploy_timeout: 45
primary_role: web
