[project]
name = "docs"
version = "0.1.0"
description = "InvenioRDM Starter Documentation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-git-revision-date-localized-plugin>=1.4.7",
    "mkdocs-material>=8.5.11",
]
