name: Mkdocs Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
      - name: Install dependencies
        run: pip install mkdocs-material
      - run: mkdocs build
