on:
  workflow_dispatch:
  push:
    branches: ["main"]

name: Publish Documentation

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
